UPDATE spells SET summary = 'Green ray from your finger. Target takes {@damage 10d6 + 40} force damage and is disintegrated if this reduces it to 0 HP. Disintegrated creatures and their gear (except magic items) become gray dust. Can only be restored with {@spell true resurrection} or {@spell wish}. Automatically disintegrates Large or smaller nonmagical objects. Huge or larger: 10-foot-cube portion.' WHERE slug = 'disintegrate';
UPDATE spells SET summary = 'You mark an object (≤10 lbs, ≤6 feet). Later, crush the sapphire and speak the item''s name to summon it to your hand instantly, regardless of distance or planes. If another creature holds it, you learn who and their location instead. {@spell Dispel magic}} ends the spell''s effect.' WHERE slug = 'drawmij's-instant-summons';
UPDATE spells SET summary = 'Ward 30-90 foot area for 1 year if cast daily. {@spell Dispel magic}} removes one effect.
Fog: heavily obscured, 2 extra feet movement cost.
Grasping undergrowth: like {@spell entangle}}.
Guardians: up to four {@creature awakened tree||trees}} fight intruders.
Other: {@spell dancing lights}}, {@spell magic mouth}}, {@spell stinking cloud}}, or {@spell barkskin}}' WHERE slug = 'druid-grove';
UPDATE spells SET summary = 'Your eyes become inky voids for the duration. One creature within 60 feet must succeed Wisdom save or be affected:
Asleep: {@condition unconscious}} until damaged or shaken awake.
Panicked: {@condition frightened}}, must {@action Dash}} away for 60+ feet.
Sickened: Disadvantage on attacks and checks; new save at turn end.' WHERE slug = 'eyebite';
UPDATE spells SET summary = 'Find the shortest physical route to a fixed location you know on same plane. Fails if target moves, is on another plane, or unspecific. For duration, know distance and direction; always determine shortest route when presented with path choices.' WHERE slug = 'find-the-path';
UPDATE spells SET summary = 'One creature in range must make Constitution save. On failure: {@condition restrained}} as flesh hardens. Must save again at turn end. Three saves total: three successes = spell ends, three failures = {@condition petrified}} for duration. Track successes and failures separately. Maintain concentration to make petrification permanent.' WHERE slug = 'flesh-to-stone';
UPDATE spells SET summary = 'Ward 40,000 sq ft (30 feet high). Prevents teleportation, portals, and planar travel. Choose creature types (celestials, elementals, fey, fiends, undead): they take {@damage 5d10}} radiant or necrotic damage entering or starting turn in area. Designate password for immunity. Cast daily 30 days same location = permanent.' WHERE slug = 'forbiddance';
UPDATE spells SET summary = 'Ward 2,500 sq ft (20 feet high). Multiple effects:
Fog (heavily obscured, 50% disoriented).
Doors locked (disguise 10 as walls).
Webs on stairs (regrow in 10 min).
Other: {@spell dancing lights}} (4), {@spell magic mouth}} (2), {@spell stinking cloud}} (2), {@spell gust}} (4), or {@spell web}} (2). Specify unaffected creatures and password.' WHERE slug = 'guards-and-wards';
UPDATE spells SET summary = 'Create feast for up to 12 creatures (1 hour to consume). Each gains: cured of diseases/poison, immune to poison and {@condition frightened}}, advantage on Wisdom saves, max HP increases {@dice 2d10}}, gain that many HP. Benefits last 24 hours.' WHERE slug = 'heroes'-feast';
UPDATE spells SET summary = 'Bright light 30 feet, dim 30 more. Immunity to fire, resistance to cold. Creatures within 5 feet take {@damage 1d10}} fire on first entry/turn end. Action: 15-foot line, 5 feet wide. Creatures save or take {@damage 4d8}} fire (half on success).' WHERE slug = 'investiture-of-flame';
UPDATE spells SET summary = 'Immune to cold, resistant to fire. Move across ice difficult terrain freely. 10-foot radius around you is difficult terrain for others. Action: 15-foot cone, creatures save or take {@damage 4d6}} cold (half on success). Failed save: speed halved until next turn start.' WHERE slug = 'investiture-of-ice';
UPDATE spells SET summary = 'Resistance to nonmagical B/P/S damage. Action: 15-foot radius earthquake, creatures save or knocked {@condition prone}}. Move through earth/stone freely. Move across difficult earth/stone freely. Ending in solid matter: ejected to nearest space, spell ends, {@condition stunned}} until next turn.' WHERE slug = 'investiture-of-stone';
UPDATE spells SET summary = 'Ranged attacks have disadvantage. Flying speed 60 feet (fall if spell ends while flying). Action: 15-foot cube anywhere within 60 feet. Creatures save or take {@damage 2d10}} bludgeoning (half on success). Large or smaller creatures: also pushed 10 feet from cube center on failed save.' WHERE slug = 'investiture-of-wind';
UPDATE spells SET summary = 'Your soul enters jar; body catatonic. Project soul up to 100 feet to possess humanoid (Charisma save; fail = you control, their soul trapped). Retain your INT/WIS/CHA and alignment; use target''s stats. Trapped soul perceives but can''t act. Return to jar (within 100 feet) as action. Target dies = CHA save or die.' WHERE slug = 'magic-jar';
UPDATE spells SET summary = 'Suggest course of action (1-2 sentences) to up to 12 creatures that can hear/understand. Charmed immunity = unaffected. Must sound reasonable; obviously harmful = negated. Wisdom save: failure = pursues suggestion for duration or until completed. Condition can trigger special activity. Damage to creature ends spell for it.' WHERE slug = 'mass-suggestion';
UPDATE spells SET summary = 'Bind creature in illusory cell it alone perceives. Intelligence save. Success: {@damage 5d10}} psychic damage, spell ends. Failure: {@damage 5d10}} psychic damage, surrounded by illusion, {@condition restrained}}. Moving out, attacking through, or reaching out: {@damage 10d10}} psychic damage, spell ends.' WHERE slug = 'mental-prison';
UPDATE spells SET summary = 'Reshape dirt/sand/clay in 40-foot area. Raise/lower elevation, dig trenches, build walls/pillars. Max extent = half area''s largest dimension. Takes 10 minutes. Every 10 minutes on concentration = new area. Creatures usually not trapped/injured. Doesn''t manipulate stone; structures shift or may collapse.' WHERE slug = 'move-earth';
UPDATE spells SET summary = 'Frigid globe to 60-foot radius. Creatures save or take {@damage 10d6}} cold (half on success). Strikes water = 6 inches ice, 30-foot square, 1 minute (swimming creatures trapped; Strength check to free). Can hold globe instead, throw later (40 feet or sling). After 1 minute: explodes.' WHERE slug = 'otiluke's-freezing-sphere';
UPDATE spells SET summary = 'One creature shuffles and taps feet in place. Charmed immunity = immune. Uses all movement dancing (no leaving space), disadvantage on Dex saves and attacks. Others gain advantage vs it. Action: Wisdom save to regain control and end spell.' WHERE slug = 'otto's-irresistible-dance';
UPDATE spells SET summary = 'Beseech god, primordial, demon, or cosmic being for celestial/elemental/fiend ally. Offer payment (100gp/min, 1000gp/hr, 10000gp/day). No compulsion; can refuse. Allied tasks cost half; dangerous tasks cost more. Refuses suicidal tasks. Nonmagical barrier/dispel ends spell after 1 minute. Task complete = creature leaves.' WHERE slug = 'planar-ally';
UPDATE spells SET summary = 'Create 30-foot cube illusion that activates on condition. Up to 5 minutes scripted performance. Dormant 10 minutes after, then reactivates. Condition: visual/audible within 30 feet. Physical contact reveals illusion; Investigation check vs spell DC to recognize it. Recognized: can see/hear through (sounds hollow).' WHERE slug = 'programmed-illusion';
UPDATE spells SET summary = 'Trap humanoid soul in cage (6 uses max; sixth releases it). Prevents corpse revival.
Steal Life (bonus): Regain {@dice 2d8}} HP.
Query Soul: ask question, get brief answer.
Borrow Experience (bonus): next attack/check/save advantage.
Eyes of Dead (action): name location soul saw, create invisible sensor (concentration, 10 min).' WHERE slug = 'soul-cage';
UPDATE spells SET summary = 'Summon {@creature Fiendish Spirit|TCE}}. Choose Demon, Devil, or Yugoloth form. Ally to you; shares your initiative. Obeys verbal commands (no action). Disappears at 0 HP or spell end. Without commands: {@action Dodge}} and avoid danger.' WHERE slug = 'summon-fiend';
UPDATE spells SET summary = '5-foot wide, 60-foot line of brilliant light. Creatures save or take {@damage 6d8}} radiant damage and {@condition blinded}} until your next turn (half damage, no blind on success). Undead and oozes have disadvantage. Action each turn: new line. Sheds bright 30 feet, dim 30 more (sunlight).' WHERE slug = 'sunbeam';
UPDATE spells SET summary = 'Lower or Upper Planes transformation. Immune to fire+poison or radiant+necrotic damage. Immune to {@condition poisoned}} or {@condition charmed}}. Spectral wings: 40 feet flying speed. +2 AC. Weapon attacks use spellcasting ability, all attacks magical. Attack twice per {@action Attack}}, ignoring other Extra Attack.' WHERE slug = 'tasha's-otherworldly-guise';
UPDATE spells SET summary = 'Endow yourself with martial prowess. Can''t cast spells. 50 temporary HP. Advantage on weapon attacks. Weapon hit: target takes extra {@damage 2d12}} force. Proficiency in all armor, shields, weapons, STR/CON saves. Attack twice per {@action Attack}}, ignoring other Extra Attack. After: {@dc 15}} CON save or gain {@condition exhaustion}}.' WHERE slug = 'tenser's-transformation';
UPDATE spells SET summary = 'Ice wall, 1 foot thick. Hemisphere/sphere (10-foot radius) or flat surface (ten 10-foot squares). Cuts through creature: pushed to side, save or {@damage 10d6}} cold (half on success). AC 12, 30 HP per section, vulnerable to fire. Destroying section leaves frigid air; creatures passing save or {@damage 5d6}} cold (half on success).' WHERE slug = 'wall-of-ice';
UPDATE spells SET summary = 'Tough brush bristling with thorns. 60 feet long, 10 feet high, 5 thick OR 20-foot circle, 20 feet high, 5 thick. Blocks line of sight. When appears: creatures save or {@damage 7d8}} piercing (half on success). Move through: 1 foot costs 4 feet movement. First entry/turn end: save or {@damage 7d8}} slashing (half on success).' WHERE slug = 'wall-of-thorns';
UPDATE spells SET summary = 'You and up to 10 willing creatures become gaseous wisps. Flying speed 300 feet, resistance to nonmagical damage. Only actions: {@action Dash}} or revert to normal (1 minute, {@condition incapacitated}}). In cloud when spell ends: descend 60 feet/round for 1 minute (lands safely). Can''t land = fall remaining distance.' WHERE slug = 'wind-walk';
UPDATE spells SET summary = 'You and up to 5 willing creatures within 5 feet teleport to sanctuary. Appear nearest unoccupied space to sanctuary spot. Must have designated sanctuary by casting spell in temple dedicated/linked to your deity. Casting in non-dedicated area = spell has no effect.' WHERE slug = 'word-of-recall';
UPDATE spells SET summary = 'Summon {@filter celestial CR 4 or lower|bestiary|challenge rating=[&0;&4]|type=celestial|miscellaneous=!swarm}} in unoccupied space. Friendly to you; disappears at 0 HP or spell end. Roll initiative; obeys verbal commands matching alignment. No commands: defends itself. DM has creature stats.' WHERE slug = 'conjure-celestial';
