UPDATE spells SET summary = 'Up to 10 nonmagical objects become creatures under your control (Medium = 2 objects, Large = 4, Huge = 8). Each has 30 ft speed or 30 ft flying speed if no limbs. Use bonus action to command them within 500 feet. If commanded to attack, each makes slam attack dealing damage by size. Objects revert when reduced to 0 HP. Creatures have 30-ft blindsight, no vision beyond.' WHERE slug = 'animate-objects';
UPDATE spells SET summary = 'You create a Large hand of force (AC 20, HP equal to your max HP). Each turn, use a bonus action to move it up to 60 feet and use one effect:
- Clenched Fist: Strike creature/object within 5 ft, {@damage 4d8} force damage
- Forceful Hand: Push Medium or smaller creature up to 5 ft + (5 × CHA mod)
- Grasping Hand: Grapple Huge or smaller; crush for {@damage 2d6} + CHA mod bludgeoning damage
- Interposing Hand: Provide you with half cover against target' WHERE slug = 'bigby's-hand';
UPDATE spells SET summary = 'Call forth elemental servant (CR 5 or lower) of Air, Earth, Fire, or Water type. It''s friendly and obeys your verbal commands. If you lose {@status concentration||concentration}, it becomes hostile and uncontrolled. Uncontrolled elemental lasts 1 hour, then disappears. DM has elemental''s statistics.' WHERE slug = 'conjure-elemental';
UPDATE spells SET summary = 'Melee spell attack; on hit, target is {@condition poisoned}. End of each of target''s turns, it must save. After 3 saves, spell ends (cured). After 3 fails, choose disease:
- Blinding Sickness: disadvantage on Wisdom, {@condition blinded}
- Filth Fever: disadvantage on Strength
- Flesh Rot: disadvantage on Charisma, vulnerability to all damage
- Mindfire: disadvantage on Intelligence, behaves as under {@spell confusion}
- Seizure: disadvantage on Dexterity
- Slimy Doom: disadvantage on Constitution, {@condition stunned} when damaged' WHERE slug = 'contagion';
UPDATE spells SET summary = '100-foot cube of air under your control. Choose Gusts (disadvantage on ranged attacks, movement penalty if strong), Downdraft (disadvantage on ranged, creatures flying in must save or be {@condition prone}), or Updraft (fall damage halved, jump height increased 10 feet). Use action to switch effects or halt/restart effect.' WHERE slug = 'control-winds';
UPDATE spells SET summary = 'Up to 5 Small or Medium corpses within range become undead (zombie or skeleton). Each gains bonus to attack and damage equal to your spellcasting ability modifier. Use bonus action to command all, within 60 feet. Creatures follow orders until task complete or spell ends, then revert to inanimate.' WHERE slug = 'danse-macabre';
UPDATE spells SET summary = 'Shimmering energy protects you; celestials, elementals, fey, fiends, and undead have disadvantage on attacks vs you. Use action to:
- Break Enchantment: Touch creature that''s {@condition charmed}, {@condition frightened}, or possessed; remove effect
- Dismissal: Melee spell attack vs celestial/elemental/fey/fiend/undead; on hit, they save vs Charisma or return to home plane (undead to Shadowfell, fey to Feywild)' WHERE slug = 'dispel-evil-and-good';
UPDATE spells SET summary = 'Humanoid you see within range must make Wisdom save or be {@condition charmed}. While charmed, telepathic link lets you issue commands (no action). You can use action for total control of target until end of your next turn. Target gains new save when it takes damage. Spell ends on successful save.' WHERE slug = 'dominate-person';
UPDATE spells SET summary = 'Shape a creature''s dreams. You or willing ally enters trance as messenger. If target sleeps, messenger appears in dream and can converse, shape environment. Messenger can create terrifying vision (≤ 10 words) that forces Wisdom save. Failed save = nightmare, no rest benefit; target takes {@damage 3d6} psychic damage on waking. With body part of target, save has disadvantage.' WHERE slug = 'dream';
UPDATE spells SET summary = 'You touch a point and infuse an area (up to 60-foot radius) with holy or unholy power. Celestials, elementals, fey, fiends, and undead can''t enter the area or charm, frighten, or possess creatures within it. Those already affected are freed upon entering.

You can bind an extra effect: Courage (immunity to fear), Darkness/Daylight, Energy Protection/Vulnerability, Everlasting Rest (creatures that die stay dead; can''t be raised except by wish), Extradimensional Interference, Fear, Increased Potency, Peaceful Rest (can''t dream), or Emboldening Bond (gain temp HP when allies are hit).' WHERE slug = 'hallow';
UPDATE spells SET summary = 'Summon one demon (CR 5 or lower) from the Abyss for the duration. Each of demon''s turns ends, it saves vs your control (disadvantage if you know true name). Failed save = obedience. Success = uncontrolled for rest of duration. Uncontrolled demons last {@dice 1d6} rounds after you lose concentration. You can form a protective circle with spell''s blood component.' WHERE slug = 'summon-greater-demon';
UPDATE spells SET summary = '5-foot-radius sphere of water hovers up to 10 feet off ground. Creatures in it make Strength save or are {@condition restrained}, engulfed. Restrained creatures can repeat save each turn. Sphere can restrain up to 4 Medium or smaller, or 1 Large. As action, move up to 30 feet. When spell ends, sphere falls, extinguishes flames within 30 feet, creatures are {@condition prone}.' WHERE slug = 'watery-sphere';
